# Generated by Django 5.2.6 on 2025-09-20 14:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(max_length=20, verbose_name='Номер телефону')),
                ('payment_status', models.CharField(choices=[('pending', 'Очікує оплати'), ('success', 'Оплачено'), ('failed', 'Помилка оплати'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус оплати')),
                ('email_status', models.CharField(choices=[('not_sent', 'Не відправлено'), ('sent', 'Відправлено'), ('failed', 'Помилка відправки')], default='not_sent', max_length=20, verbose_name='Статус відправки листа')),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], max_length=10, verbose_name='Тип пристрою')),
                ('wayforpay_order_reference', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер замовлення WayForPay')),
                ('amount', models.DecimalField(decimal_places=2, default=1789.0, max_digits=10, verbose_name='Сума')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Замовлення квитка',
                'verbose_name_plural': 'Замовлення квитків',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
