# Generated by Django 5.2.6 on 2025-09-25 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_ticketorder_delete_order_delete_participant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=2500.0, max_digits=10),
        ),
    ]
