# Generated by Django 5.2.6 on 2025-09-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_ticketorder_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketorder',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='device_type',
            field=models.CharField(choices=[('desktop', 'Десктоп'), ('mobile', 'Мобільний')], default='desktop', max_length=10),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='email_status',
            field=models.CharField(choices=[('not_sent', 'Не надіслано'), ('sent', 'Надіслано'), ('failed', 'Помилка відправки')], default='not_sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'В очікуванні'), ('success', 'Успішно'), ('failed', 'Неуспішно')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='wayforpay_order_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
