# Generated by Django 5.2.6 on 2025-09-26 10:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_ticketorder_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Замовлення квитка', 'verbose_name_plural': 'Замовлення квитків'},
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='device_type',
            field=models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile')], max_length=10, verbose_name='Тип пристрою'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='email_status',
            field=models.CharField(choices=[('not_sent', 'Не відправлено'), ('sent', 'Відправлено'), ('failed', 'Помилка відправки')], default='not_sent', max_length=20, verbose_name='Статус відправки листа'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Очікує оплати'), ('success', 'Оплачено'), ('failed', 'Помилка оплати'), ('cancelled', 'Скасовано')], default='pending', max_length=20, verbose_name='Статус оплати'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Номер телефону'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата оновлення'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='wayforpay_order_reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер замовлення WayForPay'),
        ),
    ]
