# Generated by Django 5.2.6 on 2025-10-03 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_ticketorder_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='keycrm_lead_id',
            field=models.IntegerField(blank=True, help_text='ID ліда в KeyCRM', null=True),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
