# Generated by Django 5.2.6 on 2025-10-04 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_ticketorder_event_name_ticketorder_keycrm_lead_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='ticket_status',
            field=models.CharField(choices=[('active', 'Активний'), ('used', 'Використаний'), ('invalid', 'Недійсний')], default='active', max_length=20),
        ),
    ]
