# Generated by Django 5.2.6 on 2025-10-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_ticketorder_event_name_ticketorder_scan_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketorder',
            name='event_name',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='scan_count',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='scanned_at',
        ),
        migrations.RemoveField(
            model_name='ticketorder',
            name='scanned_by',
        ),
        migrations.DeleteModel(
            name='TicketScanLog',
        ),
    ]
