# Generated by Django 5.2.6 on 2025-10-05 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_remove_ticketorder_event_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='event_name',
            field=models.CharField(default='Grand Opening Party', max_length=255),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='scan_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='scanned_by',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='TicketScanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_by', models.CharField(blank=True, max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('was_valid', models.BooleanField()),
                ('previous_status', models.CharField(max_length=20)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_logs', to='payments.ticketorder')),
            ],
            options={
                'verbose_name': 'Лог сканування',
                'verbose_name_plural': 'Логи сканувань',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
