# Generated by Django 5.2.6 on 2025-10-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_ticketorder_event_name_ticketorder_keycrm_lead_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='event_name',
            field=models.CharField(max_length=255, default='Grand Opening Party'),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='scanned_at',
            field=models.DateTimeField(null=True, blank=True),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='scanned_by',
            field=models.CharField(max_length=100, blank=True),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='scan_count',
            field=models.IntegerField(default=0),
        ),
    ]
