# Generated by Django 5.2.6 on 2025-10-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_ticketorder_event_name_ticketorder_keycrm_lead_id_and_more'),
    ]

    operations = [

    ]
