# Generated by Django 5.2.6 on 2025-10-05 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_ticketorder_event_name_ticketorder_scan_count_and_more'),
        ('payments', '0012_add_missing_fields'),
    ]

    operations = [
    ]
