# Generated by Django 5.2.6 on 2025-10-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_merge_20251005_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='name',
            field=models.CharField(default='TestUser', max_length=100),
            preserve_default=False,
        ),
    ]
