# Generated by Django 5.2.6 on 2025-10-07 15:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_ticketorder_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='Підтверджено адміном'),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Час підтвердження'),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Підтверджено користувачем'),
        ),
    ]
