# Generated by Django 5.2.6 on 2025-10-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_ticketorder_is_verified_ticketorder_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='callback_processed',
            field=models.BooleanField(default=False, help_text='Чи оброблено callback від WayForPay'),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='keycrm_payment_id',
            field=models.IntegerField(blank=True, help_text='ID платежу в KeyCRM', null=True),
        ),
    ]
