# Generated by Django 5.2.6 on 2025-10-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_ticketorder_callback_processed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketorder',
            name='keycrm_contact_id',
            field=models.IntegerField(blank=True, help_text='ID контакту в KeyCRM', null=True),
        ),
    ]
