# Generated by Django 5.2.6 on 2025-10-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_ticketorder_keycrm_contact_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'В очікуванні'), ('success', 'Успішно'), ('failed', 'Неуспішно')], default='pending', max_length=20)),
                ('device_type', models.CharField(choices=[('desktop', 'Десктоп'), ('mobile', 'Мобільний')], default='desktop', max_length=10)),
                ('wayforpay_order_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Замовлення підписки',
                'verbose_name_plural': 'Замовлення підписок',
                'ordering': ['-created_at'],
            },
        ),
    ]
