# Generated by Django 5.2.6 on 2025-10-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0018_subscriptionorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionorder',
            name='keycrm_contact_id',
            field=models.IntegerField(blank=True, help_text='ID контакту в KeyCRM', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='keycrm_lead_id',
            field=models.IntegerField(blank=True, help_text='ID ліда в KeyCRM', null=True),
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='keycrm_payment_id',
            field=models.IntegerField(blank=True, help_text='ID платежу в KeyCRM', null=True),
        ),
    ]
