# Generated by Django 5.2.6 on 2025-10-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0019_subscriptionorder_keycrm_contact_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionorder',
            name='callback_processed',
            field=models.BooleanField(default=False, help_text='Чи оброблено callback від WayForPay'),
        ),
    ]
