# Generated by Django 5.2.6 on 2025-10-22 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_subscriptionorder_callback_processed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='PASUE Club - Grand Opening Party', max_length=255)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.CharField(blank=True, help_text='Наприклад: 17:00-20:00', max_length=50)),
                ('location', models.CharField(blank=True, help_text='Місце проведення', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('max_tickets', models.PositiveIntegerField(default=50, help_text='Ліміт квитків')),
                ('is_active', models.BooleanField(default=True, help_text='Позначити поточну активну подію')),
            ],
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='ticket_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.event'),
        ),
    ]
