# Generated by Django 5.2.6 on 2025-10-22 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0021_event_ticketorder_ticket_number_ticketorder_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проведення'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Позначити поточну подію як активну', verbose_name='Активна подія'),
        ),
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=255, verbose_name='Місце проведення'),
        ),
        migrations.AlterField(
            model_name='event',
            name='max_tickets',
            field=models.PositiveIntegerField(default=50, verbose_name='Ліміт квитків'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10, verbose_name='Ціна квитка'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.CharField(blank=True, help_text='Наприклад: 17:00-20:00', max_length=50, verbose_name='Час проведення'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(default='PASUE Club - Grand Opening Party', max_length=255, verbose_name='Назва події'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payments.event', verbose_name='Подія'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='ticket_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер квитка'),
        ),
    ]
