# Generated by Django 5.2.6 on 2025-10-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_alter_event_date_alter_event_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketorder',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'In pending'), ('success', 'Success'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
