# Generated by Django 5.2.6 on 2025-10-23 17:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0023_alter_ticketorder_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('funnel_tag', models.CharField(default='default', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_tokens', to='payments.ticketorder')),
            ],
        ),
    ]
