# Generated by Django 5.2.6 on 2025-10-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0024_botaccesstoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1559.0, max_digits=10, verbose_name='Ціна квитка'),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1559.0, max_digits=10),
        ),
    ]
