# Generated by Django 5.2.6 on 2025-11-21 07:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0025_alter_event_price_alter_ticketorder_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionBotAccessToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('funnel_tag', models.CharField(default='subscription-default', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_tokens', to='payments.subscriptionorder')),
            ],
        ),
    ]
