# Generated by Django 5.2.6 on 2025-12-15 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0026_subscriptionbotaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionorder',
            name='utm_campaign',
            field=models.CharField(blank=True, default='', help_text='Назва кампанії', max_length=255, verbose_name='UTM Campaign'),
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='utm_content',
            field=models.CharField(blank=True, default='', help_text='Варіант оголошення', max_length=255, verbose_name='UTM Content'),
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='utm_medium',
            field=models.CharField(blank=True, default='', help_text='Канал трафіку', max_length=255, verbose_name='UTM Medium'),
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='utm_source',
            field=models.CharField(blank=True, default='', help_text='Джерело трафіку', max_length=255, verbose_name='UTM Source'),
        ),
        migrations.AddField(
            model_name='subscriptionorder',
            name='utm_term',
            field=models.CharField(blank=True, default='', help_text='Ключове слово', max_length=255, verbose_name='UTM Term'),
        ),
    ]
