# Generated by Django 5.2.6 on 2026-01-03 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0027_subscriptionorder_utm_campaign_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_reference', models.CharField(db_index=True, help_text='OrderReference першого платежу, під яким створена регулярка в WayForPay', max_length=100, unique=True, verbose_name='WayForPay OrderReference')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='Імʼя')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Телефон')),
                ('mode', models.CharField(blank=True, default='', max_length=32, verbose_name='Regular mode')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Сума')),
                ('currency', models.CharField(blank=True, default='', max_length=8, verbose_name='Валюта')),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('suspended', 'Suspended'), ('removed', 'Removed'), ('completed', 'Completed'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=16, verbose_name='Статус')),
                ('date_begin', models.DateTimeField(blank=True, null=True, verbose_name='Початок')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Завершення')),
                ('last_payed_date', models.DateTimeField(blank=True, null=True, verbose_name='Останній платіж')),
                ('last_payed_status', models.CharField(blank=True, default='', max_length=64, verbose_name='Статус останнього платежу')),
                ('next_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Наступний платіж')),
                ('last_reason', models.CharField(blank=True, default='', max_length=255, verbose_name='Причина/повідомлення')),
                ('last_reason_code', models.IntegerField(blank=True, null=True, verbose_name='Reason code')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Остання синхронізація')),
                ('last_sync_raw', models.JSONField(blank=True, null=True, verbose_name='Остання відповідь WayForPay (raw)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscriptions', to='payments.subscriptionorder', verbose_name='Початкове замовлення')),
            ],
            options={
                'verbose_name': 'Підписка',
                'verbose_name_plural': 'Підписки',
                'ordering': ['-updated_at'],
            },
        ),
    ]
